### ISSUE TITLE
Maintainership.

### ISSUE THREAD

**Issue by fbrausse** [fbrausse/ltl2c#1]
@lucasccordeiro

As the creator and maintainer of this repository, it would be good if my privileges to manage it would be restored. Thanks.

![image](https://github.com/user-attachments/assets/c983ec6e-4203-4c08-9529-f1b63b3fef3e)

Meanwhile, the latest version can be found on https://github.com/fbrausse/libltl2ba

**Comment by lucasccordeiro** [comment]
@fbrausse: You should be able to access this ltl2ba repo. Please let me know if it works.

**Comment by fbrausse** [comment]
I've accepted the invitation. However, "write-access" is not the same as maintainance of a repo. If you want to do it yourself or have someone else in mind, please go ahead. But in that case I would ask you to change the name of this project in order to avoid confusion with the one I created and am maintaining.

**Comment by lucasccordeiro** [comment]
Updated as requested.
